version: '3.7'

services:
  app:
    build:
      context: .   
    network_mode: host
    volumes: 
      - static_data:/vol/web   
    environment: 
      - DEBUG=0
   
  proxy:
    build: 
      context: ./proxy
    network_mode: host  
    volumes: 
      - static_data:/vol/static
    depends_on: 
      - app

volumes: 
  static_data:
